repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: check-toml
      - id: pretty-format-json
        args: ["--autofix"]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        files: acg
        args: [ "--in-place" ]
  - repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
      - id: isort
        files: acg
        types: [python]
        exclude: google_images_download
  - repo: https://github.com/PyCQA/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint
        files: acg
        types: [python]
        exclude: (google_images_download|__init__.py)
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 5.1.1
    hooks:
      - id: pydocstyle
        files: acg
        args: [--add-ignore,"D105,D107"] #Docstrings for __init__ and other magic functions.
        exclude: (google_images_download|__init__.py)
  - repo: https://github.com/codespell-project/codespell
    rev: v2.0.0
    hooks:
      - id: codespell
        files: acg
        types: [text]
        args: [-q, "4",-D, -, -D, .codespell_dict.txt, -H]
        exclude: google_images_download
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
    hooks:
      - id: pyupgrade
        files: acg
        types: [python]
        args: [--py38-plus]
        exclude: google_images_download
  - repo: https://github.com/Yelp/detect-secrets
    rev: v0.14.3
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json, google_images_download
        files: acg
