repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/pylint
    rev: pylint-2.5.0
    hooks:
      - id: pylint
        args: [--rcfile=./.pylintrc]
        files: acg
        types: [python]
        exclude: (google_images_download|__init__.py)
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 5.0.2
    hooks:
      - id: pydocstyle
        exclude: (google_images_download|__init__.py)
        files: acg
        args: [--add-ignore,"D105,D107"] #Docstrings for __init__ and other magic functions.
  - repo: https://github.com/codespell-project/codespell
    rev: "v1.17.1"
    hooks:
      - id: codespell
        files: acg
        verbose: True
        exclude: (google_images_download|_build)
        types: [text]
        args: [-q, "4",-D, -, -D, .codespell_dict.txt, -H]
  - repo: local
    hooks:
      - id: render_readme
        name: render_readme.py
        entry: .utils/render_readme.py
        language: system
        stages: [commit]
        always_run: True
