repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/pylint
#  - repo: local
    rev: pylint-2.5.0
    hooks:
      - id: pylint
#        name: pylint
#        entry: pylint
#        language: system
        args: [--rcfile=.pre-commit/.pylintrc]
        files: src
        types: [python]
        exclude: (google_images_download|python-for-android)
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 5.0.2
    hooks:
      - id: pydocstyle
        exclude: (google_images_download|python-for-android)
        files: src
        args: [--add-ignore,"D105,D107"] #Docstrings for __init__ and other magic functions.
  - repo: https://github.com/codespell-project/codespell
    rev: "v1.17.1"
    hooks:
      - id: codespell
        files: src
        verbose: True
        exclude: google_images_download
        types: [text]
        args: [-q, "4",-D, -, -D, .pre-commit/dictionary.txt, -H]
  - repo: local
    hooks:
      - id: take_screenshots
        name: screenshots
        entry: .pre-commit/screenshots.py
        stages: [push,merge-commit]
        language: system
        pass_filenames: False
        always_run: True
      - id: render_readme
        name: render_readme.py
        entry: .pre-commit/render_readme.py
        language: system
        stages: [commit]
        always_run: True
