#!/bin/bash

word=$@
folder=${word// /_}

path=~/gen_ank/

cd $path
if [ -d "$folder" ]; then
  echo "Exiting..."
  exit 1
fi

mkdir $folder

python3 /usr/local/lib/python3.6/dist-packages/google_images_download/google_images_download.py -k "$word" -l 3 -o $path -f jpg -la Spanish

i=1
for x in ./"$word"/*
	do convert "$x" -resize x300 "${folder}/$i.jpg"
	rm "$x"
	((++i))

done

