#:import SingleWordRoot screens.single_word.SingleWordRoot
SingleWordRoot:
    id: single_word_root
    scroll_view: scroll_view
    template: app.template

    ScrollView:
        id: scroll_view
        do_scroll_x: False
        do_scroll_y: True
        size_hint: 1,1

    MDFloatingActionButton:
        icon: "check-bold"
        pos: (root.width-dp(16)-self.width,dp(10))
        on_press: word_prop.complete_generation()
