name: build android apk
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: master

      - name: Build with Buildozer
        uses: david-fischer/buildozer-action@v1
        id: buildozer
        with:
          repository_root: master
          workdir: .
          buildozer_version: stable
          command: buildozer android debug

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: data
          ref: data # Branch name

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64

      - name: Push binary to data branch
        run: python master/.ci/move_binary.py "${{ steps.buildozer.outputs.filename }}" master data
