name: build linux

on:
  release:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: AnkiCardGen
        path: src/dist/linux

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: data
        ref: data # Branch name

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: x64

    - name: Push binary to data branch
      run: python master/.ci/move_binary.py "src/dist/linux/AnkiCardGen" master data linux
