name: build linux

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:
    name: build for linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: master
        ref: master

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: master/acg
        spec: pyinstaller.spec

#    - uses: actions/upload-artifact@v2
#      with:
#        name: AnkiCardGen
#        path: acg/dist/linux

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: data
        ref: data # Branch name

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: x64

    - name: debug
      run: ls master/acg; for x in master/acg/*; do echo $x; ls $x; done

    - name: Push binary to data branch
      run: python master/.ci/move_binary.py "master/acg/dist/linux/AnkiCardGen" master data linux
