name: build linux

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:
    name: build for linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: master
        ref: master

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64

    - name: Install Dependencies
      run: pip install ./master

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: master
        spec: pyinstaller.spec

#    - uses: actions/upload-artifact@v2
#      with:
#        name: AnkiCardGen
#        path: acg/dist/linux

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: data
        ref: data # Branch name


#    - name: debug
#      run: ls master/acg/dist/linux

    - name: zip
      run: cd master/acg/dist/linux; zip -r AnkiCardGen.zip AnkiCardGen; cd -

    - name: Push zipped app to data branch
      run: python master/.utils/move_binary.py "master/acg/dist/linux/AnkiCardGen.zip" master data linux
