name: build linux

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: master
        ref: master

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: master/src
        spec: pyinstaller-linux.spec

#    - uses: actions/upload-artifact@v2
#      with:
#        name: AnkiCardGen
#        path: src/dist/linux

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: data
        ref: data # Branch name

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: x64

    - name: Push binary to data branch
      run: python master/.ci/move_binary.py "master/src/dist/linux/AnkiCardGen" master data linux
