name: pyinstaller poetry

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:
    name: build for linux
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: data
        ref: data

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: master
        ref: master

    - name: Package Application
      uses: david-fischer/pyinstaller_poetry@master
      with:
        path: master
        spec: pyinstaller.spec
        out_dir: dist/linux
        pre_package_hook: "python -m spacy download pt"

#    - name: debug
#      run: ls master; ls master/dist; ls master/dist/linux;

    - name: zip
      run: cd master/dist/linux/AnkiCardGen; zip -r AnkiCardGen.zip AnkiCardGen; cd -

    - name: Push zipped app to data branch
      run: python master/.utils/move_binary.py "master/dist/linux/AnkiCardGen.zip" master data linux
