name: build windows

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: master
        ref: master

    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: master/src
        spec: pyinstaller-windows.spec


#    - uses: actions/upload-artifact@v2
#      with:
#        name: AnkiCardGen
#        path: src/dist/windows # or path/to/artifact

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: data
        ref: data # Branch name

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: x64

    - name: Push binary to data branch
      run: python master/.ci/move_binary.py "master/src/dist/windows/AnkiCardGen.exe" master data windows
