name: test

on:
  release:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: data
        ref: data # Branch name

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: x64

    - name: ls
      run: ls ..; ls data

    - name: Push binary to data branch
      run: python master/.ci/move_binary.py "src/dist/linux/AnkiCardGen" master data linux
